# .github/release.yml

changelog:
  exclude:
    labels:
      - 'rel: ignore'
  categories:
    - title: New Features
      labels:
        - 'rel: new feature'

    - title: Improvements
      labels:
        - 'rel: improvement'

    - title: Fixes
      labels:
        - 'rel: fix'

    - title: Other Changes
      labels:
        - '*'
