trigger:
- main

pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo 'VUE_APP_PUBLIC_PATH="/"' >> .env

      mkdir WEB-INF
      cat > WEB-INF/web.xml <<EOL
        <?xml version="1.0" encoding="UTF-8"?>
        <web-app xmlns="http://java.sun.com/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd" version="3.0">
        <description>Delft-FEWS Web OC</description>
        <!-- For the web oc all 404 errors need to redirect to the index.html page. -->
        <error-page>
        <error-code>404</error-code>
        <location>/index.html</location>
        </error-page>
        </web-app>
      EOL
#      Overwrite the app config.
      cat > public/app-config.json <<EOL
      {
        "VUE_APP_FEWS_WEBSERVICES_URL": "http://localhost:8080/FewsWebServices",
        "VUE_APP_MAPBOX_TOKEN": "get a token at: https://account.mapbox.com/access-tokens",
        "_VUE_APP_AUTH_AUTHORITY": "https://login.microsoftonline.com/MYTENANTID/",
        "_VUE_APP_AUTH_ID": "app registration id",
        "_VUE_APP_AUTH_TYPE": "code",
        "_VUE_APP_AUTH_SCOPE": "openid"
      }
      EOL

- script: |
    npm install
    npm run build
  displayName: 'npm install and build of Web Operator Client deployed in the root.'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '/'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/weboc-root-$(Build.BuildId).zip'
    replaceExistingArchive: true