trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/*
      - package.json

pr: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.5.x'
    displayName: 'Install Node.js'
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        touch .env
        echo 'VITE_PUBLIC_PATH="/"' >> .env

        rm public/app-config.json      
        cat > public/app-config.json <<EOL
        {
        "VITE_FEWS_WEBSERVICES_URL": "$(VITE_FEWS_WEBSERVICES_URL)",
        "VITE_MAPBOX_TOKEN": "$(VITE_MAPBOX_TOKEN)",
        "VITE_REQUEST_HEADER_AUTHORIZATION": "Off",
        "VITE_AUTH_AUTHORITY": "$(VITE_AUTH_AUTHORITY)",
        "VITE_AUTH_ID": "$(VITE_AUTH_ID)",
        "VITE_AUTH_METADATA_URL": "https://login.microsoftonline.com/$(AZURE_TENANT_ID)/v2.0/.well-known/openid-configuration",
        "VITE_AUTH_SCOPE": "openid profile email Offline_Access api://$(AZURE_CLIENT_ID)/Delft-FEWSWebServices"            
        }

  - script: |
      cp docs/public/deployments/azure/staticwebapp.config.json .
      npm install
      npm --version
      node --version
      npm run build
      rm -rf $(System.DefaultWorkingDirectory)/dist
    displayName: 'npm install and build of Web Operator Client'
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      api_location: ''
      output_location: '$(System.DefaultWorkingDirectory)/dist'
      skip_app_build: true
      app_build_command: 'npm run build'
      azure_static_web_apps_api_token: $(deployment_token)
