trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/*
      - package.json

pr: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.5.x'
    displayName: 'Install Node.js'
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        touch .env
        echo 'VITE_PUBLIC_PATH="/"' >> .env

        rm public/app-config.json      
        cat > public/app-config.json <<EOL
        {
        "VITE_FEWS_WEBSERVICES_URL": "$(VITE_FEWS_WEBSERVICES_URL)"
        }
  - script: |
      npm install
      npm --version
      node --version
      npm run build
      cp docs/public/deployments/azure/staticwebapp.config.json dist
    displayName: 'npm install and build of Web Operator Client'
  - task: AzureStaticWebApp@0
    inputs:
      # When used with skip_app_build: true, this value is the app's build output location.
      app_location: '/dist'
      api_location: ''
      skip_app_build: 'true'
      verbose: 'true'
      azure_static_web_apps_api_token: $(deployment_token)
