name: Deploy Web OC dev applications.
#
# To add a new deployment target, you need to:
# 1. Add a new repository secret with the name of the deployment target and the value of the Azure Static Web Apps API token.
# 2. Add a new repository varaibel with the name of the deployment target and the value of the app-config.json file in base64 format.
#

permissions:
  contents: read

on:
  push:
    branches:
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 22
      - run: npm ci
      - name: Run unit tests
        run: npm run test:unit

      - name: Build distribution
        run: npm run build

      - name: Create the staticwebapp.config.json file
        run: |
          cat > dist/staticwebapp.config.json <<EOL
          {
            "navigationFallback": {
              "rewrite": "index.html"
            }
          }
          EOL
          touch dist/app-config.json
        shell: bash

      - name: Create the app-config.json file for the Pulau Tekong Secured App
        run: |
          rm dist/app-config.json
          echo "${{ vars.PULAU_TEKONG_DEV_APP_CONFIG_JSON_BASE64 }}" | base64 --decode > dist/app-config.json
        shell: bash
      - name: Deploy Azure Static Web Apps Pulau Tekong
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          action: 'upload'
          app_location: '/dist'
          api_location: ''
          skip_app_build: true
          azure_static_web_apps_api_token: ${{ secrets.PULAU_TEKONG_DEV_APP_AZURE_STATIC_WEB_APP_TOKEN }}

      - name: Create the app-config.json file for Durban App
        run: |
          rm dist/app-config.json
          echo "${{ vars.DURBAN_DEV_APP_CONFIG_JSON_BASE64 }}" | base64 --decode > dist/app-config.json
        shell: bash
      - name: Deploy Azure Static Web Apps Durban App
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          action: 'upload'
          app_location: '/dist'
          api_location: ''
          skip_app_build: true
          azure_static_web_apps_api_token: ${{ secrets.DURBAN_DEV_APP_AZURE_STATIC_WEB_APP_TOKEN }}
