name: Deploy the Web OC test applications.

on:
#  push:
#    branches: ['main']
#    paths:
#      - src/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci

      - name: Run unit tests
        run: npm run test

      - name: Overwrite the app-config.json file
        run: |
          rm public/app-config.json
          echo "${{ secrets.IWP_PUBLIC_APP_CONFIG_JSON }}" > public/app-config.json <<EOL

      - name: Build distribution
        run: npm run build

      - name: Build And Deploy Azure Static Web Apps IWP Public App
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          action: "upload"
          app_location: '/dist'
          api_location: ''
          skip_app_build: true
          verbose: 'true'
          azure_static_web_apps_api_token: ${{ secrets.IWP_PUBLIC_APP_AZURE_STATIC_WEB_APP_TOKEN }}
