name: Upload assets on new release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - base: /
            asset_name: dist
          - base: /weboc/
            asset_name: dist-weboc
    steps:
      - uses: actions/checkout@v7
      - name: Setup Node.js 24
        uses: actions/setup-node@v7
        with:
          node-version: 24
      - run: npm ci --ignore-scripts
      - run: npm run patch-package

      - run: npm run build -- --base=${{ matrix.base }}
      - run: zip -r ${{ matrix.asset_name }} dist

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./${{ matrix.asset_name }}.zip
